//! MCP prompts: the four workflows an association's volunteers actually run.
//!
//! A prompt here is a script, not a personality. Each one names the tools to
//! call, in order, and where to stop and ask. The rule they share: read before
//! writing, and never move money without an explicit yes.

use rmcp::{
    ErrorData as McpError,
    handler::server::{router::prompt::PromptRouter, wrapper::Parameters},
    model::{PromptMessage, Role},
};
use serde::Deserialize;

use crate::server::HelloAssoServer;

/// Arguments of `treasury_report`.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct ReportArgs {
    /// The period: `last month` (the default), `this year`, `2026-09`…
    pub period: Option<String>,
}

/// Arguments of `find_person`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct PersonArgs {
    /// A name or an email.
    pub who: String,
}

/// Arguments of `attendee_list`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct FormPromptArgs {
    /// The form's URL, or its slug.
    pub form: String,
}

/// Arguments of `refund_request`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct RefundArgs {
    /// Who asks for a refund: a name, an email, or a payment or order id.
    pub who: String,
    /// Why, in the person's words, if known.
    pub reason: Option<String>,
}

/// The prompt router this server exposes.
pub fn router() -> PromptRouter<HelloAssoServer> {
    HelloAssoServer::prompt_router()
}

#[allow(missing_docs, reason = "the router function is generated by the macro")]
#[rmcp::prompt_router]
impl HelloAssoServer {
    /// A treasurer's report over a period: what was collected, per campaign,
    /// per means and per month, with refunds and anomalies. Reads only.
    #[rmcp::prompt(name = "treasury_report")]
    pub async fn treasury_report_prompt(
        &self,
        Parameters(args): Parameters<ReportArgs>,
    ) -> std::result::Result<Vec<PromptMessage>, McpError> {
        let period = args.period.unwrap_or_else(|| "last month".to_owned());
        let text = format!(
            "Write the treasury report of my association on HelloAsso for {period}. \
             This is a read-only exercise: do not create, change, refund or cancel anything.\n\
             \n\
             1. `whoami`, to name the organization.\n\
             2. `summarize_payments` with period = \"{period}\" for the totals: collected, per form, \
                per payment means, per month, and refunds.\n\
             3. `list_forms` to put a human title on each form slug in the breakdown.\n\
             4. If anything looks odd (refused or contested payments, refunds, a form collecting \
                nothing), `list_payments` with the matching `states` over the same period to show \
                the lines behind it.\n\
             \n\
             Then present: the total collected in euros (amounts from the API are cents: divide by 100), \
             a table per campaign, the split per means, the refunds, and three lines on what stands out. \
             Use French number formatting (1 234,50 €)."
        );
        Ok(vec![PromptMessage::new_text(Role::User, text)])
    }

    /// Everything one person did with the association: memberships, tickets,
    /// donations, payments, and whether they are up to date. Reads only.
    #[rmcp::prompt(name = "find_person")]
    pub async fn find_person_prompt(
        &self,
        Parameters(args): Parameters<PersonArgs>,
    ) -> std::result::Result<Vec<PromptMessage>, McpError> {
        let who = args.who;
        let text = format!(
            "Find everything \"{who}\" did with my association on HelloAsso. Read only.\n\
             \n\
             1. `list_items` with search = \"{who}\" and with_details = true: memberships, tickets, \
                donations, with the answers to each form's questions.\n\
             2. `list_payments` with search = \"{who}\": what they paid, when, and the state of each payment, \
                including future instalments (Pending).\n\
             3. If several people match, list them and ask me which one before going further.\n\
             \n\
             Then tell me: who they are (name, email), their current membership and until when if the \
             form says, the events they registered for, what they paid in total (in euros: the API speaks \
             cents), and anything pending, refused or refunded."
        );
        Ok(vec![PromptMessage::new_text(Role::User, text)])
    }

    /// The attendee or member list of one form, with the answers to its
    /// questions, ready to print or check in. Reads only.
    #[rmcp::prompt(name = "attendee_list")]
    pub async fn attendee_list_prompt(
        &self,
        Parameters(args): Parameters<FormPromptArgs>,
    ) -> std::result::Result<Vec<PromptMessage>, McpError> {
        let form = args.form;
        let text = format!(
            "Build the attendee list of the HelloAsso form \"{form}\". Read only.\n\
             \n\
             1. `get_form` (pass it as form_url if it is a URL, otherwise find it with `list_forms`) \
                for the title, the date and the tiers.\n\
             2. `get_form_stats` for the totals per tier.\n\
             3. `list_form_items` with item_states = [\"Processed\", \"Registered\"] and with_details = true, \
                walking every page with continuation_token, so nobody is missed.\n\
             \n\
             Present a table sorted by last name: participant, tier, amount in euros, the answers to \
             the custom fields, and the payer when it is someone else. End with the count per tier \
             and check it against the statistics; say so if they disagree."
        );
        Ok(vec![PromptMessage::new_text(Role::User, text)])
    }

    /// Handle a refund request: find the payment, check what can be refunded,
    /// propose, and refund only after an explicit yes.
    #[rmcp::prompt(name = "refund_request")]
    pub async fn refund_request_prompt(
        &self,
        Parameters(args): Parameters<RefundArgs>,
    ) -> std::result::Result<Vec<PromptMessage>, McpError> {
        let who = args.who;
        let reason = args
            .reason
            .map(|r| format!(" The reason given: \"{r}\"."))
            .unwrap_or_default();
        let text = format!(
            "\"{who}\" asks for a refund on HelloAsso.{reason}\n\
             \n\
             1. Find the payment: `get_payment` or `get_order` if you were given an id, otherwise \
                `list_payments` with search = \"{who}\". If several payments could be meant, list them and ask.\n\
             2. `get_order` with check_refund_eligibility = true, to see what the order holds, whether \
                future instalments remain, and whether the payment can still be refunded.\n\
             3. Propose: which payment, full or partial (amount in euros, and in cents for the API), \
                whether to cancel the remaining instalments too (`cancel_order` on the order), and whether \
                HelloAsso should email the payer.\n\
             4. **Stop and wait for my explicit agreement.** A refund sends real money back and cannot be undone.\n\
             5. Once I agree, call `refund_payment` with confirm = true. If HelloAsso answers with an MFA \
                error, tell me which code it needs and wait for me to give it to you.\n\
             6. Read the payment back with `get_payment` and show me its refund operations."
        );
        Ok(vec![PromptMessage::new_text(Role::User, text)])
    }
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        reason = "a test that cannot fail loudly is not a test"
    )]

    #[test]
    fn the_four_workflows_are_exposed_and_described() {
        let prompts = super::router().list_all();
        let names: Vec<String> = prompts.iter().map(|p| p.name.clone()).collect();
        assert_eq!(prompts.len(), 4, "{names:?}");
        for expected in [
            "treasury_report",
            "find_person",
            "attendee_list",
            "refund_request",
        ] {
            assert!(
                names.contains(&expected.to_owned()),
                "{expected} is missing"
            );
        }
        for prompt in prompts {
            let description = prompt
                .description
                .as_deref()
                .unwrap_or_else(|| panic!("{} has no description", prompt.name));
            assert!(description.len() > 30, "{}: {description:?}", prompt.name);
        }
    }
}
