//! The checkout flow: a payment link for an amount, and its outcome.
//!
//! `create_checkout_intent` answers a `redirectUrl` to send the payer to.
//! Once they have paid, `get_checkout_intent` shows the order it produced.

use rmcp::{ErrorData as McpError, Json, handler::server::wrapper::Parameters};
use serde::Deserialize;
use serde_json::{Map, Value};

use crate::{
    client::Request,
    error::Error,
    server::HelloAssoServer,
    tools::{ApiObject, Body, QueryBuilder, ok, positive},
};

/// A future instalment.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct Term {
    /// The instalment's amount, in cents.
    pub amount_cents: i64,
    /// When it is taken, `YYYY-MM-DD`.
    pub date: String,
}

/// Who pays, to prefill the payment page.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct Payer {
    /// First name.
    pub first_name: Option<String>,
    /// Last name.
    pub last_name: Option<String>,
    /// Email.
    pub email: Option<String>,
    /// Date of birth, `YYYY-MM-DD`.
    pub date_of_birth: Option<String>,
    /// Street address.
    pub address: Option<String>,
    /// City.
    pub city: Option<String>,
    /// Postal code.
    pub zip_code: Option<String>,
    /// Three-letter country code, e.g. FRA.
    pub country: Option<String>,
    /// The company's name, when a company pays.
    pub company_name: Option<String>,
}

/// Arguments of `create_checkout_intent`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct CreateCheckoutArgs {
    /// The organization slug. Defaults to the configured organization.
    pub organization: Option<String>,
    /// What the payer pays for, shown on the payment page and the receipt
    /// ("2026 membership", "3 tickets"). At most 250 characters.
    pub item_name: String,
    /// The total, in cents, all taxes included. Must equal the initial amount
    /// plus every term.
    pub total_amount_cents: i64,
    /// The first instalment, in cents. Defaults to the total when there are no
    /// terms.
    pub initial_amount_cents: Option<i64>,
    /// Later instalments, for a payment in several times.
    pub terms: Option<Vec<Term>>,
    /// Where the payer goes back to if they leave the payment page.
    pub back_url: String,
    /// Where the payer lands after an error.
    pub error_url: String,
    /// Where the payer lands after paying. HelloAsso appends `checkoutIntentId`,
    /// `code` and `orderId`.
    pub return_url: String,
    /// True when all or part of the sale is a donation (tax receipts).
    pub contains_donation: bool,
    /// Prefill the payer's details.
    pub payer: Option<Payer>,
    /// Any JSON object, kept with the checkout and returned with the order
    /// (an internal reference, a member id…). At most 20 000 characters.
    pub metadata: Option<Map<String, Value>>,
    /// Offer SEPA direct debit as well as card.
    pub enable_sepa: Option<bool>,
}

/// Arguments of `get_checkout_intent`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct GetCheckoutArgs {
    /// The organization slug. Defaults to the configured organization.
    pub organization: Option<String>,
    /// The checkout intent id, as returned by `create_checkout_intent`.
    pub checkout_intent_id: i64,
    /// Also list refund attempts that failed.
    pub with_failed_refund_operation: Option<bool>,
}

fn require_url(name: &str, url: &str) -> Result<String, Error> {
    let url = url.trim();
    if url.starts_with("https://") || url.starts_with("http://localhost") {
        Ok(url.to_owned())
    } else {
        Err(Error::invalid(format!(
            "{name} must be an absolute https:// URL, got {url:?}"
        )))
    }
}

#[allow(missing_docs, reason = "the router function is generated by the macro")]
#[rmcp::tool_router(router = checkout_router, vis = "pub")]
impl HelloAssoServer {
    /// Create a payment link for an amount in cents, paid at once or in
    /// instalments, and get the `redirectUrl` to send the payer to. Nothing is
    /// charged until the payer pays on HelloAsso's page.
    #[rmcp::tool(annotations(
        title = "Create a checkout",
        read_only_hint = false,
        destructive_hint = false,
        idempotent_hint = false,
        open_world_hint = true
    ))]
    pub async fn create_checkout_intent(
        &self,
        Parameters(args): Parameters<CreateCheckoutArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let item_name = args.item_name.trim();
        if item_name.is_empty() || item_name.chars().count() > 250 {
            return Err(Error::invalid("item_name must hold 1 to 250 characters").into());
        }
        positive("total_amount_cents", args.total_amount_cents)?;
        let terms = args.terms.unwrap_or_default();
        let terms_total: i64 = terms.iter().map(|t| t.amount_cents).sum();
        let initial = args
            .initial_amount_cents
            .unwrap_or(args.total_amount_cents - terms_total);
        positive("initial_amount_cents", initial)?;
        if initial + terms_total != args.total_amount_cents {
            return Err(Error::invalid(format!(
                "total_amount_cents ({}) must equal initial_amount_cents ({initial}) plus the terms ({terms_total})",
                args.total_amount_cents
            ))
            .into());
        }
        let mut term_values = Vec::with_capacity(terms.len());
        for term in &terms {
            positive("a term's amount_cents", term.amount_cents)?;
            term_values.push(serde_json::json!({
                "amount": term.amount_cents,
                "date": crate::dates::iso(crate::dates::date(&term.date)?),
            }));
        }
        if let Some(metadata) = &args.metadata
            && serde_json::to_string(metadata).map_or(0, |s| s.len()) > 20_000
        {
            return Err(Error::invalid("metadata exceeds HelloAsso's 20 000 characters").into());
        }
        let payer = args.payer.map(|p| {
            Body::new()
                .opt("firstName", p.first_name)
                .opt("lastName", p.last_name)
                .opt("email", p.email)
                .opt("dateOfBirth", p.date_of_birth)
                .opt("address", p.address)
                .opt("city", p.city)
                .opt("zipCode", p.zip_code)
                .opt("country", p.country)
                .opt("companyName", p.company_name)
                .build()
        });
        let org = self
            .resolver()
            .organization(args.organization.as_deref())
            .await?;
        let body = Body::new()
            .set("totalAmount", args.total_amount_cents)
            .set("initialAmount", initial)
            .set("itemName", item_name)
            .set("backUrl", require_url("back_url", &args.back_url)?)
            .set("errorUrl", require_url("error_url", &args.error_url)?)
            .set("returnUrl", require_url("return_url", &args.return_url)?)
            .set("containsDonation", args.contains_donation)
            .opt("terms", (!term_values.is_empty()).then_some(term_values))
            .opt("payer", payer)
            .opt("metadata", args.metadata.map(Value::Object))
            .opt(
                "paymentOptions",
                args.enable_sepa
                    .map(|sepa| serde_json::json!({ "enableSepa": sepa })),
            )
            .build();
        let created: Value = self
            .client()
            .call(Request::post(format!("/organizations/{org}/checkout-intents")).json(body))
            .await?;
        ok(ApiObject::from_value(created))
    }

    /// Read a checkout intent: its metadata, its redirect URL, and the order it
    /// produced once the payer has paid. No `order` means not paid (yet).
    #[rmcp::tool(annotations(
        title = "Get a checkout",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn get_checkout_intent(
        &self,
        Parameters(args): Parameters<GetCheckoutArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let id = positive("checkout_intent_id", args.checkout_intent_id)?;
        let org = self
            .resolver()
            .organization(args.organization.as_deref())
            .await?;
        let query = QueryBuilder::new()
            .opt(
                "withFailedRefundOperation",
                args.with_failed_refund_operation,
            )
            .build();
        let intent: Value = self
            .client()
            .call(Request::get(format!("/organizations/{org}/checkout-intents/{id}")).query(query))
            .await?;
        ok(ApiObject::from_value(intent))
    }
}
