//! The organization itself, the organizations this client reaches, and the
//! reference lists HelloAsso publishes.

use rmcp::{ErrorData as McpError, Json, handler::server::wrapper::Parameters};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{
    client::Request,
    config::Credentials,
    server::HelloAssoServer,
    tools::{ApiObject, Listing, ok},
};

/// What `whoami` answers with.
#[derive(Debug, Clone, Serialize, schemars::JsonSchema)]
pub struct WhoAmI {
    /// `production` or `sandbox`.
    pub environment: String,
    /// The API root in use.
    pub base_url: String,
    /// `client_credentials` or `static_token`.
    pub authentication: String,
    /// The API client id, shortened.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The organization tools act on when none is given.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_organization: Option<String>,
    /// That organization's public profile, when it could be read.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organization: Option<Value>,
    /// The organizations this client holds a role on, and the role.
    pub reachable_organizations: Vec<Value>,
    /// The toolsets exposed.
    pub toolsets: Vec<String>,
    /// True when every write tool is withheld.
    pub read_only: bool,
    /// What did not work while gathering this, if anything.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
}

/// Arguments of a tool that reads one organization.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct OrganizationArgs {
    /// The organization slug, as in `helloasso.com/associations/{slug}`, or
    /// that URL. Defaults to the configured organization.
    pub organization: Option<String>,
}

/// No arguments.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct NoArgs {}

#[allow(missing_docs, reason = "the router function is generated by the macro")]
#[rmcp::tool_router(router = organization_router, vis = "pub")]
impl HelloAssoServer {
    /// Who this server acts as: the environment, the API client, the default
    /// organization and its profile, and every organization the client holds a
    /// role on. Call it first.
    #[rmcp::tool(annotations(title = "Who am I", read_only_hint = true, open_world_hint = true))]
    pub async fn whoami(
        &self,
        Parameters(_): Parameters<NoArgs>,
    ) -> std::result::Result<Json<WhoAmI>, McpError> {
        let config = self.config();
        let mut warnings = Vec::new();

        // A token failure is the one thing worth failing loudly on.
        self.client().access_token().await?;

        let reachable = match self.resolver().my_organizations().await {
            Ok(list) => list,
            Err(err) => {
                warnings.push(format!("listing reachable organizations: {err}"));
                Vec::new()
            }
        };
        let default = match self.resolver().organization(None).await {
            Ok(slug) => Some(slug),
            Err(err) => {
                warnings.push(err.to_string());
                None
            }
        };
        let organization = match &default {
            Some(slug) => match self
                .client()
                .call::<Value>(Request::get(format!("/organizations/{slug}")))
                .await
            {
                Ok(org) => Some(org),
                Err(err) => {
                    warnings.push(format!("reading {slug}: {err}"));
                    None
                }
            },
            None => None,
        };

        ok(WhoAmI {
            environment: config.environment.as_str().to_owned(),
            base_url: config.base_url.clone(),
            authentication: match config.credentials {
                Credentials::Client { .. } => "client_credentials",
                Credentials::Token(_) => "static_token",
            }
            .to_owned(),
            client_id: config.client_id().map(|id| {
                let shown: String = id.chars().take(8).collect();
                format!("{shown}…")
            }),
            default_organization: default,
            organization,
            reachable_organizations: reachable,
            toolsets: config
                .toolsets
                .iter()
                .map(|t| t.as_str().to_owned())
                .collect(),
            read_only: config.read_only,
            warnings,
        })
    }

    /// Read an organization's public profile: name, type, category, address,
    /// description, logo, fiscal receipt eligibility, links.
    #[rmcp::tool(annotations(
        title = "Get an organization",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn get_organization(
        &self,
        Parameters(args): Parameters<OrganizationArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let slug = self
            .resolver()
            .organization(args.organization.as_deref())
            .await?;
        let org: Value = self
            .client()
            .call(Request::get(format!("/organizations/{slug}")))
            .await?;
        ok(ApiObject::from_value(org))
    }

    /// List the organizations the authenticated user or client holds a role on
    /// (OrganizationAdmin or FormAdmin), with their slugs.
    #[rmcp::tool(annotations(
        title = "List my organizations",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn list_my_organizations(
        &self,
        Parameters(_): Parameters<NoArgs>,
    ) -> std::result::Result<Json<Listing>, McpError> {
        let list: Value = self
            .client()
            .call(Request::get("/users/me/organizations"))
            .await?;
        ok(Listing::from_value(list))
    }

    /// List HelloAsso's organization categories (culture, sport, education…),
    /// the reference used by the directory filters.
    #[rmcp::tool(annotations(
        title = "List organization categories",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn list_organization_categories(
        &self,
        Parameters(_): Parameters<NoArgs>,
    ) -> std::result::Result<Json<Listing>, McpError> {
        let list: Value = self
            .client()
            .call(Request::get("/values/organization/categories"))
            .await?;
        ok(Listing::from_value(list))
    }

    /// List the company legal statuses HelloAsso knows (SARL, SAS,
    /// association…), the reference for company payers.
    #[rmcp::tool(annotations(
        title = "List company legal statuses",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn list_company_legal_statuses(
        &self,
        Parameters(_): Parameters<NoArgs>,
    ) -> std::result::Result<Json<Listing>, McpError> {
        let list: Value = self
            .client()
            .call(Request::get("/values/company-legal-status"))
            .await?;
        ok(Listing::from_value(list))
    }
}
