//! Partner administration: the partner account, the organizations linked to
//! it, its OAuth redirect domain, and its notification (webhook) URLs.
//!
//! These routes only make sense with a *partner* API client, obtained from
//! HelloAsso's partnership team. An association's own client answers 403.

use rmcp::{ErrorData as McpError, Json, handler::server::wrapper::Parameters};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{
    client::Request,
    error::Error,
    server::HelloAssoServer,
    tools::{
        ApiObject, Done, Listing, QueryBuilder, api_name, directory::DirectoryPage, ok,
        organization::NoArgs, require_confirmation,
    },
};

/// The events a notification URL can be dedicated to.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, schemars::JsonSchema)]
pub enum NotificationType {
    /// A payment was made, refunded, or changed state.
    Payment,
    /// An order was placed.
    Order,
    /// A form was created or changed.
    Form,
    /// An organization was linked or changed.
    Organization,
}

/// Arguments of `list_partner_organizations`.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct PartnerOrganizationsArgs {
    /// Pagination.
    #[serde(flatten)]
    pub page: DirectoryPage,
}

/// Arguments of `update_partner_domain`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct UpdateDomainArgs {
    /// The domain OAuth redirections are allowed to, e.g. `https://app.example.org`.
    pub domain: String,
}

/// Arguments of `set_notification_url`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct SetNotificationArgs {
    /// The HTTPS URL HelloAsso will POST notifications to.
    pub url: String,
    /// Dedicate the URL to one event type. The main URL, receiving every type,
    /// when absent.
    pub notification_type: Option<NotificationType>,
}

/// Arguments of `delete_notification_url`.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct DeleteNotificationArgs {
    /// The dedicated URL to remove. The main URL when absent.
    pub notification_type: Option<NotificationType>,
    /// Must be `true`: the integration stops receiving these notifications.
    pub confirm: Option<bool>,
}

/// Arguments of `set_organization_notification_url`.
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct SetOrgNotificationArgs {
    /// The organization slug. Defaults to the configured organization.
    pub organization: Option<String>,
    /// The HTTPS URL HelloAsso will POST this organization's notifications to.
    pub url: String,
    /// Dedicate the URL to one event type. The main URL when absent.
    pub notification_type: Option<NotificationType>,
}

/// Arguments of `delete_organization_notification_url`.
#[derive(Debug, Clone, Default, Deserialize, schemars::JsonSchema)]
pub struct DeleteOrgNotificationArgs {
    /// The organization slug. Defaults to the configured organization.
    pub organization: Option<String>,
    /// The dedicated URL to remove. The main URL when absent.
    pub notification_type: Option<NotificationType>,
    /// Must be `true`: the integration stops receiving these notifications.
    pub confirm: Option<bool>,
}

fn https(name: &str, url: &str) -> Result<String, Error> {
    let url = url.trim();
    if url.starts_with("https://") && url.len() > "https://".len() {
        Ok(url.to_owned())
    } else {
        Err(Error::invalid(format!(
            "{name} must be an https:// URL, got {url:?}"
        )))
    }
}

fn notification_body(url: &str, kind: Option<NotificationType>) -> Value {
    let mut body = serde_json::json!({ "url": url });
    if let Some(kind) = kind {
        body["notificationType"] = Value::String(api_name(&kind));
    }
    body
}

fn which(kind: Option<NotificationType>) -> String {
    kind.map_or_else(
        || "main notification URL".to_owned(),
        |k| format!("{} notification URL", api_name(&k)),
    )
}

#[allow(missing_docs, reason = "the router function is generated by the macro")]
#[rmcp::tool_router(router = partner_router, vis = "pub")]
impl HelloAssoServer {
    /// Read the partner account behind this API client: name, API client
    /// settings, notification URLs and statistics. Partner clients only.
    #[rmcp::tool(annotations(
        title = "Get the partner account",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn get_partner(
        &self,
        Parameters(_): Parameters<NoArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let partner: Value = self.client().call(Request::get("/partners/me")).await?;
        ok(ApiObject::from_value(partner))
    }

    /// List the organizations that authorized this partner, oldest update
    /// first, walked with `continuation_token`. Partner clients only.
    #[rmcp::tool(annotations(
        title = "List partner organizations",
        read_only_hint = true,
        open_world_hint = true
    ))]
    pub async fn list_partner_organizations(
        &self,
        Parameters(args): Parameters<PartnerOrganizationsArgs>,
    ) -> std::result::Result<Json<Listing>, McpError> {
        let query = QueryBuilder::new()
            .opt(
                "pageSize",
                Some(args.page.page_size.unwrap_or(20).clamp(1, 100)),
            )
            .opt(
                "continuationToken",
                args.page
                    .continuation_token
                    .as_deref()
                    .filter(|t| !t.trim().is_empty()),
            )
            .build();
        let page: Value = self
            .client()
            .call(Request::get("/partners/me/organizations").query(query))
            .await?;
        ok(Listing::from_value(page))
    }

    /// Change the domain this partner's OAuth redirections are allowed to.
    /// Partner clients only.
    #[rmcp::tool(annotations(
        title = "Update the partner domain",
        read_only_hint = false,
        destructive_hint = false,
        idempotent_hint = true,
        open_world_hint = true
    ))]
    pub async fn update_partner_domain(
        &self,
        Parameters(args): Parameters<UpdateDomainArgs>,
    ) -> std::result::Result<Json<Done>, McpError> {
        let domain = https("domain", &args.domain)?;
        let answer: Value = self
            .client()
            .call(
                Request::put("/partners/me/api-clients")
                    .json(serde_json::json!({ "domain": domain })),
            )
            .await?;
        ok(Done::new(format!("partner domain set to {domain}"), answer))
    }

    /// Set the partner's main notification URL, or one dedicated to Payment,
    /// Order, Form or Organization events. HelloAsso POSTs JSON to it.
    #[rmcp::tool(annotations(
        title = "Set a notification URL",
        read_only_hint = false,
        destructive_hint = false,
        idempotent_hint = true,
        open_world_hint = true
    ))]
    pub async fn set_notification_url(
        &self,
        Parameters(args): Parameters<SetNotificationArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let url = https("url", &args.url)?;
        let answer: Value = self
            .client()
            .call(
                Request::put("/partners/me/api-notifications")
                    .json(notification_body(&url, args.notification_type)),
            )
            .await?;
        ok(ApiObject::from_value(answer))
    }

    /// Remove the partner's main notification URL, or a dedicated one.
    /// Requires `confirm: true`: the integration stops hearing from HelloAsso.
    #[rmcp::tool(annotations(
        title = "Delete a notification URL",
        read_only_hint = false,
        destructive_hint = true,
        idempotent_hint = true,
        open_world_hint = true
    ))]
    pub async fn delete_notification_url(
        &self,
        Parameters(args): Parameters<DeleteNotificationArgs>,
    ) -> std::result::Result<Json<Done>, McpError> {
        let what = which(args.notification_type);
        require_confirmation(
            args.confirm,
            &format!("the partner's {what} would be removed"),
        )?;
        let query = QueryBuilder::new()
            .opt_enum("notificationType", args.notification_type)
            .build();
        let answer: Value = self
            .client()
            .call(Request::delete("/partners/me/api-notifications").query(query))
            .await?;
        ok(Done::new(format!("partner {what} removed"), answer))
    }

    /// Set the notification URL a partner receives one organization's events
    /// on, main or dedicated to one event type. Needs OrganizationAdmin on it.
    #[rmcp::tool(annotations(
        title = "Set an organization notification URL",
        read_only_hint = false,
        destructive_hint = false,
        idempotent_hint = true,
        open_world_hint = true
    ))]
    pub async fn set_organization_notification_url(
        &self,
        Parameters(args): Parameters<SetOrgNotificationArgs>,
    ) -> std::result::Result<Json<ApiObject>, McpError> {
        let url = https("url", &args.url)?;
        let org = self
            .resolver()
            .organization(args.organization.as_deref())
            .await?;
        let answer: Value = self
            .client()
            .call(
                Request::put(format!(
                    "/partners/me/api-notifications/organizations/{org}"
                ))
                .json(notification_body(&url, args.notification_type)),
            )
            .await?;
        ok(ApiObject::from_value(answer))
    }

    /// Remove the notification URL a partner receives one organization's
    /// events on. Requires `confirm: true`.
    #[rmcp::tool(annotations(
        title = "Delete an organization notification URL",
        read_only_hint = false,
        destructive_hint = true,
        idempotent_hint = true,
        open_world_hint = true
    ))]
    pub async fn delete_organization_notification_url(
        &self,
        Parameters(args): Parameters<DeleteOrgNotificationArgs>,
    ) -> std::result::Result<Json<Done>, McpError> {
        let org = self
            .resolver()
            .organization(args.organization.as_deref())
            .await?;
        let what = which(args.notification_type);
        require_confirmation(
            args.confirm,
            &format!("the {what} for {org} would be removed"),
        )?;
        let query = QueryBuilder::new()
            .opt_enum("notificationType", args.notification_type)
            .build();
        let answer: Value = self
            .client()
            .call(
                Request::delete(format!(
                    "/partners/me/api-notifications/organizations/{org}"
                ))
                .query(query),
            )
            .await?;
        ok(Done::new(format!("{what} for {org} removed"), answer))
    }
}
